# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d845697e0376cb5496d6d8c7e1f5ef5c3b9e4bf3b1eab76e1234ea6342f9b6a9fa50d1f20a375ace429fc0a8fc4a1406656b59b48ab871ed814958e7315ce729

test:
  secret_key_base: e3e7040a26f7005a6e446ba3af59d129555e9fe6c7bbb6c9248c84167634e64f86b0a6913840a39b224768dcf96c9faa31850722b5ebcc616e8611ab602fd29b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
